// Package firewall renders an nftables config for a node given a) the
// custom firewall_rules entries that target it (or all nodes) and b) the
// auto-rules synthesized from carriers/client_ips so SIP from those sources
// is allowed without manual entry.
package firewall

import (
	"fmt"
	"sort"
	"strings"
)

// Rule is the renderer's view of a single rule. Maps 1:1 to a row in
// firewall_rules with action ∈ {allow, block, rate_limit}.
type Rule struct {
	Name          string
	Action        string // allow | block | rate_limit
	SourceCIDR    string // empty = any
	DestPortLow   int    // 0 = any
	DestPortHigh  int    // 0 = same as low (single port)
	Proto         string // any | tcp | udp
	RatePerSecond int    // only for rate_limit
	Notes         string
}

// AutoRule is the data we know about an external source the node should
// accept SIP from (a carrier endpoint or a client dialer IP).
type AutoRule struct {
	Kind  string // "carrier" | "client_dialer"
	Name  string // carrier name or client name
	CIDR  string // 1.2.3.4/32  or  1.2.3.0/24
}

// NodeContext is what the renderer needs to know about the node being
// rendered for.
type NodeContext struct {
	NodeID      int64
	NodeName    string
	Role        string   // media | sip_proxy
	HostIP      string   // management IP
	BaseAppCIDR string   // base-app source IP/CIDR (always allowed for SSH)
	SIPPort     int      // 5060 typically
	RTPLow      int      // 30000
	RTPHigh     int      // 60000
	// SipProxyIPs: management IPs of every active sip_proxy node. Used on
	// media-role render to whitelist UDP/2223 (rtpengine NG control) from
	// those sources, so kamailio on the SipProxy can reach this MediaNode's
	// rtpengine. Without this, calls relay signaling fine but media never
	// negotiates because rtpengine_manage() in kamailio gets no reply.
	SipProxyIPs []string
}

// Render produces a complete nftables config as a single string.
// Output is a self-contained `nft -f`-loadable file.
func Render(ctx NodeContext, rules []Rule, autoRules []AutoRule) string {
	var b strings.Builder

	fmt.Fprintf(&b, "#!/usr/sbin/nft -f\n")
	fmt.Fprintf(&b, "# Auto-generated by mediaproxy panel for node #%d (%s, role=%s)\n", ctx.NodeID, ctx.NodeName, ctx.Role)
	fmt.Fprintf(&b, "# Apply with:  sudo nft -f /etc/mediaproxy/firewall.nft\n")
	fmt.Fprintf(&b, "# Default policy is DROP — only listed sources can reach SIP/RTP.\n\n")
	fmt.Fprintf(&b, "flush ruleset\n\n")

	fmt.Fprintf(&b, "table inet mediaproxy {\n")

	// ----- SIP allowlist set -----
	uniqCidrs := map[string]struct{}{}
	for _, a := range autoRules {
		uniqCidrs[a.CIDR] = struct{}{}
	}
	sortedAuto := make([]string, 0, len(uniqCidrs))
	for c := range uniqCidrs {
		sortedAuto = append(sortedAuto, c)
	}
	sort.Strings(sortedAuto)

	fmt.Fprintf(&b, "  set sip_allowlist {\n")
	fmt.Fprintf(&b, "    type ipv4_addr\n")
	fmt.Fprintf(&b, "    flags interval\n")
	if len(sortedAuto) > 0 {
		fmt.Fprintf(&b, "    elements = {\n")
		for i, c := range sortedAuto {
			sep := ","
			if i == len(sortedAuto)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "      %s%s\n", c, sep)
		}
		fmt.Fprintf(&b, "    }\n")
	}
	fmt.Fprintf(&b, "  }\n\n")

	// Per-rule blocklist for explicit deny rules (action='block')
	hasExplicitBlock := false
	for _, r := range rules {
		if r.Action == "block" && r.SourceCIDR != "" {
			hasExplicitBlock = true
			break
		}
	}
	if hasExplicitBlock {
		fmt.Fprintf(&b, "  set blocked_sources {\n")
		fmt.Fprintf(&b, "    type ipv4_addr\n")
		fmt.Fprintf(&b, "    flags interval\n")
		blockedCIDRs := []string{}
		for _, r := range rules {
			if r.Action == "block" && r.SourceCIDR != "" {
				blockedCIDRs = append(blockedCIDRs, r.SourceCIDR)
			}
		}
		sort.Strings(blockedCIDRs)
		fmt.Fprintf(&b, "    elements = {\n")
		for i, c := range blockedCIDRs {
			sep := ","
			if i == len(blockedCIDRs)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "      %s%s\n", c, sep)
		}
		fmt.Fprintf(&b, "    }\n")
		fmt.Fprintf(&b, "  }\n\n")
	}

	// ----- input chain -----
	fmt.Fprintf(&b, "  chain input {\n")
	fmt.Fprintf(&b, "    type filter hook input priority 0; policy drop;\n\n")

	fmt.Fprintf(&b, "    iif lo accept comment \"loopback\"\n")
	fmt.Fprintf(&b, "    ct state established,related accept comment \"established\"\n")
	fmt.Fprintf(&b, "    ct state invalid drop comment \"invalid\"\n\n")

	// ICMP
	fmt.Fprintf(&b, "    icmp type echo-request limit rate 5/second accept comment \"icmp ping (rate-limited)\"\n")
	fmt.Fprintf(&b, "    icmpv6 type echo-request limit rate 5/second accept\n\n")

	// SSH from base-app (always) + any global allows
	fmt.Fprintf(&b, "    tcp dport 22 accept comment \"ssh\"\n\n")

	// Hard-drop blocked sources first (precedence over allows)
	if hasExplicitBlock {
		fmt.Fprintf(&b, "    ip saddr @blocked_sources drop comment \"explicit block list\"\n\n")
	}

	// Sort custom rules by priority then name
	sortedRules := make([]Rule, len(rules))
	copy(sortedRules, rules)
	sort.SliceStable(sortedRules, func(i, j int) bool {
		return sortedRules[i].Action != "block" && sortedRules[j].Action == "block"
	})

	for _, r := range sortedRules {
		if r.Action == "block" {
			// already handled via the set above
			continue
		}
		renderRule(&b, r)
	}

	// ----- SIP via allowlist -----
	if len(sortedAuto) > 0 {
		fmt.Fprintf(&b, "\n    # SIP signaling (auto-allowlist: carriers + client dialer IPs)\n")
		fmt.Fprintf(&b, "    udp dport %d ip saddr @sip_allowlist accept comment \"sip udp\"\n", ctx.SIPPort)
		fmt.Fprintf(&b, "    tcp dport %d ip saddr @sip_allowlist accept comment \"sip tcp\"\n", ctx.SIPPort)
		fmt.Fprintf(&b, "    udp dport %d drop comment \"sip from unauthorized source\"\n", ctx.SIPPort)
		fmt.Fprintf(&b, "    tcp dport %d drop comment \"sip from unauthorized source\"\n\n", ctx.SIPPort)
	} else {
		fmt.Fprintf(&b, "\n    # NO SIP allowlist sources known — no SIP rule emitted. Add carriers / client dialer IPs to enable inbound SIP.\n\n")
	}

	// ----- RTP (only for media role) -----
	if ctx.Role == "media" {
		fmt.Fprintf(&b, "    # RTP media range — RTPEngine validates per-call membership; firewall only opens the port range.\n")
		fmt.Fprintf(&b, "    udp dport %d-%d accept comment \"rtp\"\n\n", ctx.RTPLow, ctx.RTPHigh)

		// rtpengine NG control socket. Allow only from known sip_proxy
		// mgmt IPs. If no sip_proxy nodes exist yet, emit a comment
		// instead of an empty allowlist that would no-op.
		sortedSP := append([]string(nil), ctx.SipProxyIPs...)
		sort.Strings(sortedSP)
		if len(sortedSP) > 0 {
			fmt.Fprintf(&b, "    # rtpengine NG control (UDP/2223) from sip_proxy nodes\n")
			fmt.Fprintf(&b, "    udp dport 2223 ip saddr { %s } accept comment \"rtpengine NG from sip_proxy\"\n\n",
				strings.Join(sortedSP, ", "))
		} else {
			fmt.Fprintf(&b, "    # rtpengine NG (2223): no sip_proxy nodes registered yet, nothing to allow\n\n")
		}
	}

	fmt.Fprintf(&b, "    # Anything else → drop (implicit by policy drop above)\n")
	fmt.Fprintf(&b, "  }\n")
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

func renderRule(b *strings.Builder, r Rule) {
	parts := []string{}

	if r.Proto != "" && r.Proto != "any" {
		parts = append(parts, r.Proto)
	}
	if r.DestPortLow > 0 {
		switch {
		case r.DestPortHigh > 0 && r.DestPortHigh != r.DestPortLow:
			parts = append(parts, fmt.Sprintf("dport %d-%d", r.DestPortLow, r.DestPortHigh))
		default:
			parts = append(parts, fmt.Sprintf("dport %d", r.DestPortLow))
		}
	}
	if r.SourceCIDR != "" {
		parts = append(parts, "ip saddr "+r.SourceCIDR)
	}

	var verdict string
	switch r.Action {
	case "rate_limit":
		rate := r.RatePerSecond
		if rate <= 0 {
			rate = 10
		}
		verdict = fmt.Sprintf("limit rate %d/second accept", rate)
	case "allow":
		verdict = "accept"
	default:
		verdict = "drop"
	}

	fmt.Fprintf(b, "    %s %s comment %q\n", strings.Join(parts, " "), verdict, r.Name)
}
