package agent

import (
	"fmt"
	"net/url"
	"os"
	"sort"
	"strconv"
	"strings"
)

// GenKamailioConfig writes the listen.cfg fragment (one listen= per signaling
// IP) and the main kamailio.cfg that:
//   - calls our /route endpoint via http_async_client
//   - forces outbound INVITEs from the chosen signaling IP via $fs
//   - rewrites media via rtpengine_manage()
//   - relays to the chosen carrier
//   - mirrors every SIP message as HEP3 to the base-app's heplify-server
//     (used by HOMER for SIP-ladder inspection)
//
// SIP-layer hardening (pike per-source CPS, htable blocklist, drop scanner UAs)
// is built in.
//
// listenIPs is the set of signaling IPs bound on this node (already deduped).
// nodeID is used as the HEP capture-id so HOMER can attribute messages to
// the right proxy when multiple SipProxy nodes are in play.
// KamailioGenOpts bundles the scale-tuning knobs so we don t grow
// GenKamailioConfig s positional arg list every time we add a tunable.
// Zero values mean "use the in-template default" (see assignDefaults).
type KamailioGenOpts struct {
	Children          int // udp worker count
	TCPChildren       int // tcp worker count
	RouteCacheSeconds int // 0 = disable cache, >0 = enable with TTL
	// RouteCacheKeyLen: leading-digit count of DNIS to include in cache
	// key. 0 = full DNIS (safe). 3 = country-code-only (faster, requires
	// routing rules with prefix length <= 3). See TUNING.md.
	RouteCacheKeyLen int
}

func GenKamailioConfig(listenIPs []string, controlPlaneURL, agentToken string, nodeID int64, rtpengineSock string, opts KamailioGenOpts) (listenCfg string, mainCfg string) {
	uniq := make([]string, 0, len(listenIPs))
	seen := map[string]struct{}{}
	for _, ip := range listenIPs {
		if _, dup := seen[ip]; dup || ip == "" {
			continue
		}
		seen[ip] = struct{}{}
		uniq = append(uniq, ip)
	}
	sort.Strings(uniq)

	var lb strings.Builder
	fmt.Fprintf(&lb, "# Generated by mediaproxy node-agent. Do not edit by hand.\n")
	for _, ip := range uniq {
		fmt.Fprintf(&lb, "listen=udp:%s:5060\n", ip)
		fmt.Fprintf(&lb, "listen=tcp:%s:5060\n", ip)
	}
	listenCfg = lb.String()

	// HEP destination = the host part of the control-plane URL. heplify-server
	// listens on UDP/9060 on the base-app; kamailio resolves the hostname at
	// load time. If parsing fails we leave it blank and the template will
	// render "sip:" — siptrace just won't push anything, which is the right
	// degraded mode (don't break call routing because HEP capture is unhappy).
	hepHost := ""
	if u, err := url.Parse(controlPlaneURL); err == nil {
		hepHost = u.Hostname()
	}

	// rtpengine wiring. If sock points anywhere but our localhost stub,
	// we assume rtpengine is reachable and turn the rtpengine_manage()
	// calls back on (request route + reply route). When sock is the
	// default "udp:127.0.0.1:2223" — i.e. no remote MediaNode wired up
	// — leave the calls commented out so kamailio doesn't spam
	// "no available proxies" ERROR every reply.
	if rtpengineSock == "" {
		rtpengineSock = "udp:127.0.0.1:2223"
	}
	rtpengineEnabled := rtpengineSock != "udp:127.0.0.1:2223" && rtpengineSock != "udp:127.0.0.1:2222"
	// rtpengine_manage() auto-detects offer vs answer from script context,
	// but the detection is broken inside an http_async_client suspended
	// callback (route[ROUTE_REPLY]) — it picks 'delete' instead of 'offer'
	// for the INVITE side, leaving the outbound SDP unrewritten. Carrier
	// then sees the dialer's IP/port and audio bypasses MediaNode entirely.
	// Fix: call rtpengine_offer() / rtpengine_answer() explicitly so no
	// detection is involved.
	//
	// Interface selection: the modern kamailio rtpengine module uses
	// `direction=any;<NAME>` in the flags string. This sets the rtpengine
	// NG `direction` list to ["any", "<NAME>"] — first element is the
	// inbound iface (we don't care, "any"), second is the outbound
	// iface NAME we want. With named interfaces in rtpengine.conf
	// (NAME/IP form), <NAME> matches the iface and rtpengine binds the
	// outbound RTP socket on that IP. The older `out-iface=` key is
	// silently ignored by rtpengine 11+ ("Unknown dictionary key"
	// warning in syslog) — that's why every call egressed on the
	// first listed interface.
	manageReq := `# rtpengine_offer("replace-origin replace-session-connection direction=any direction=" + $var(m_ip));`
	manageRpl := `# if (status =~ "(180|183|200)") {
    #     rtpengine_answer();
    # }`
	if rtpengineEnabled {
		// Two `direction=` tokens in the flags string — kamailio's
		// rtpengine module accumulates them into the NG `direction`
		// bencode list. The first goes to position 0 (incoming /
		// internal), the second to position 1 (outgoing / external).
		// rtpengine then binds the outbound RTP socket on whichever
		// named interface matches the second entry.
		manageReq = `rtpengine_offer("replace-origin replace-session-connection direction=any direction=" + $var(m_ip));`
		manageRpl = `if (status =~ "(180|183|200)") {
        rtpengine_answer();
    }`
	}

	deleteOnBye := "# rtpengine_delete();  // disabled — sock is localhost stub"
	if rtpengineEnabled {
		deleteOnBye = "rtpengine_delete();"
	}

	// Defaults for tunables (caller may pass zero values).
	children := opts.Children
	if children <= 0 {
		children = 16
	}
	tcpChildren := opts.TCPChildren
	if tcpChildren <= 0 {
		tcpChildren = 4
	}

	// /route cache snippet. When enabled, request_route checks an
	// htable BEFORE doing the async HTTP call. On hit, we synthesise
	// the same callback by jumping to ROUTE_REPLY with $http_rb stashed.
	// Hit rate is high because dialers grind through long blocks of
	// same-prefix numbers; same client+prefix hits the cache 95%+ of
	// the time. Removes the per-INVITE HTTP RTT from the hot path —
	// single biggest throughput multiplier.
	routeCacheCheck := "# /route cache disabled (route_cache_seconds=0)"
	routeCacheStore := "# /route cache disabled"
	routeCacheHtable := "# /route cache disabled"
	if opts.RouteCacheSeconds > 0 {
		ttl := strconv.Itoa(opts.RouteCacheSeconds)
		routeCacheHtable = `modparam("htable", "htable", "rcache=>size=12;autoexpire=` + ttl + `")`
		// DNIS substring length: 0 = full DNIS (safe default), N>0 = first N digits.
		// Most operators want 0; bump only if your routing config matches
		// on country code (e.g. all 31xxx → carrier-A) AND you've verified
		// no longer-prefix rules.
		var dnisExpr string
		if opts.RouteCacheKeyLen > 0 {
			dnisExpr = "$(rU{s.substr,0," + strconv.Itoa(opts.RouteCacheKeyLen) + "})"
		} else {
			dnisExpr = "$rU"
		}
		var dnisOrigExpr string
		if opts.RouteCacheKeyLen > 0 {
			dnisOrigExpr = "$(var(dnis_orig){s.substr,0," + strconv.Itoa(opts.RouteCacheKeyLen) + "})"
		} else {
			dnisOrigExpr = "$var(dnis_orig)"
		}
		// On cache hit, unpack the 7 parsed routing fields (pipe-separated)
		// from rcache, populate $var()s, and jump straight to DO_RELAY.
		// $http_rb is read-only in Kamailio so we cannot fake the
		// async-reply path — instead we cache parsed values and call
		// the relay subroutine directly. ROUTE_REPLY does the same call
		// after parsing the live /route JSON, so both paths share code.
		routeCacheCheck = `# Cache key = dialer src IP + DNIS (configurable substring).
    $var(rckey) = $si + ":" + ` + dnisExpr + `;
    if ($sht(rcache=>$var(rckey)) != $null) {
        $var(packed) = $sht(rcache=>$var(rckey));
        $var(client_id)  = $(var(packed){s.select,0,|});
        $var(carrier_id) = $(var(packed){s.select,1,|});
        $var(c_host)     = $(var(packed){s.select,2,|});
        $var(c_port)     = $(var(packed){s.select,3,|});
        $var(c_xport)    = $(var(packed){s.select,4,|});
        $var(m_ip)       = $(var(packed){s.select,5,|});
        $var(sig_ip)     = $(var(packed){s.select,6,|});
        $var(dnis_orig)  = $rU;
        $var(ani_orig)   = $fU;
        $sht(call=>$ci::dnis) = $rU;
        $sht(call=>$ci::ani)  = $fU;
        $sht(call=>$ci::sig)  = $si;
        t_newtran();
        if ($retcode == 0) { exit; }
        if ($retcode < 0)  { sl_reply_error(); exit; }
        t_reply("100", "Trying");
        route(DO_RELAY);
        exit;
    }`
		routeCacheStore = `# Store parsed routing fields packed pipe-separated, for next INVITE.
    # jansson_get returns integers as numeric type; leading "" forces
    # string concat (Kamailio's + would otherwise try int arithmetic and
    # fail on missing/string fields).
    if ($var(dnis_orig) != $null && $sht(call=>$ci::sig) != $null && $var(c_host) != $null) {
        $var(rckey2) = "" + $sht(call=>$ci::sig) + ":" + ` + dnisOrigExpr + `;
        $sht(rcache=>$var(rckey2)) = "" + $var(client_id) + "|" + $var(carrier_id) + "|" + $var(c_host) + "|" + $var(c_port) + "|" + $var(c_xport) + "|" + $var(m_ip) + "|" + $var(sig_ip);
    }`
	}

	mainCfg = strings.ReplaceAll(kamailioMainTmpl, "{{CONTROL_PLANE_URL}}", controlPlaneURL)
	mainCfg = strings.ReplaceAll(mainCfg, "{{AGENT_TOKEN}}", agentToken)
	mainCfg = strings.ReplaceAll(mainCfg, "{{HOMER_HEP_HOST}}", hepHost)
	mainCfg = strings.ReplaceAll(mainCfg, "{{HOMER_CAPTURE_ID}}", strconv.FormatInt(nodeID, 10))
	mainCfg = strings.ReplaceAll(mainCfg, "{{RTPENGINE_SOCK}}", rtpengineSock)
	mainCfg = strings.ReplaceAll(mainCfg, "{{RTPENGINE_MANAGE_REQUEST}}", manageReq)
	mainCfg = strings.ReplaceAll(mainCfg, "{{RTPENGINE_MANAGE_REPLY}}", manageRpl)
	mainCfg = strings.ReplaceAll(mainCfg, "{{RTPENGINE_DELETE_ON_BYE}}", deleteOnBye)
	mainCfg = strings.ReplaceAll(mainCfg, "{{KAMAILIO_CHILDREN}}", strconv.Itoa(children))
	mainCfg = strings.ReplaceAll(mainCfg, "{{KAMAILIO_TCP_CHILDREN}}", strconv.Itoa(tcpChildren))
	mainCfg = strings.ReplaceAll(mainCfg, "{{ROUTE_CACHE_HTABLE}}", routeCacheHtable)
	mainCfg = strings.ReplaceAll(mainCfg, "{{ROUTE_CACHE_CHECK}}", routeCacheCheck)
	mainCfg = strings.ReplaceAll(mainCfg, "{{ROUTE_CACHE_STORE}}", routeCacheStore)
	return
}

// WriteKamailioConfigs writes both files iff their contents differ from
// what's already on disk. Returns changed=true if either file was actually
// rewritten, so the caller can decide whether to bounce the service.
//
// Why: Kamailio's stock systemd unit doesn't support config reload — every
// `systemctl reload-or-restart` is a full restart. With heartbeat at 10s
// the agent was cycling Kamailio every 10s in steady state, which made
// Asterisk's 5s qualify pings half-miss → trunk marked UNREACHABLE →
// CHANUNAVAIL on every Dial(). Skipping the write+restart when the
// content is identical fixes the loop.
func WriteKamailioConfigs(listenPath, mainPath, listenCfg, mainCfg string) (changed bool, err error) {
	if err := os.MkdirAll("/etc/kamailio", 0o755); err != nil {
		return false, err
	}
	listenChanged, err := writeIfChanged(listenPath, listenCfg)
	if err != nil {
		return false, fmt.Errorf("write %s: %w", listenPath, err)
	}
	mainChanged, err := writeIfChanged(mainPath, mainCfg)
	if err != nil {
		return false, fmt.Errorf("write %s: %w", mainPath, err)
	}
	return listenChanged || mainChanged, nil
}

// writeIfChanged compares wanted content to whatever's already on disk and
// writes only on mismatch. Returns true if a write happened.
func writeIfChanged(path, wanted string) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == wanted {
		return false, nil
	}
	if err := os.WriteFile(path, []byte(wanted), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

const kamailioMainTmpl = `#!KAMAILIO
####### mediaproxy SIP proxy (auto-generated; do not edit) #######
# - per-call route lookup via http_async_client → control plane
# - force-send-socket to per-client signaling IP
# - rtpengine for media rewrite
# - pike + htable scanner block + UA filter

#!define MULTIDOMAIN 0
debug=2
log_stderror=no
log_facility=LOG_LOCAL0
fork=yes
# Worker counts driven by config.yaml (kamailio_children / kamailio_tcp_children).
# Defaults 16/4 — see TUNING.md for sizing by concurrent-call target.
children={{KAMAILIO_CHILDREN}}
tcp_children={{KAMAILIO_TCP_CHILDREN}}
# Larger UDP socket recv buffer so a short worker stall doesn't drop
# packets at the kernel before kamailio can process them. Default 213k
# overflows in ~3s of burst SIP traffic.
udp_mtu=1500
auto_aliases=no
mpath="/usr/lib/x86_64-linux-gnu/kamailio/modules/"
sip_warning=no

include_file "/etc/kamailio/listen.cfg"

####### modules #######
loadmodule "tm.so"
loadmodule "sl.so"
loadmodule "rr.so"
loadmodule "pv.so"
loadmodule "maxfwd.so"
loadmodule "textops.so"
loadmodule "textopsx.so"
loadmodule "siputils.so"
loadmodule "xlog.so"
loadmodule "sanity.so"
loadmodule "ctl.so"
loadmodule "pike.so"
loadmodule "htable.so"
loadmodule "http_async_client.so"
loadmodule "jansson.so"
loadmodule "rtpengine.so"
loadmodule "siptrace.so"

####### pike: per-source-IP CPS limiter #######
modparam("pike", "sampling_time_unit", 2)
modparam("pike", "reqs_density_per_unit", 60)
modparam("pike", "remove_latency", 4)

####### htable: scanner blocklist + PDD timing + per-call snapshot #######
modparam("htable", "htable", "blocked=>size=12;autoexpire=86400")
# pdd: per-call INVITE timestamp in ms. autoexpire=120 = drop stale entries
# after 2 minutes (way longer than any plausible PDD; 18x always arrives in
# under 30s on every real route, including bad ones).
modparam("htable", "htable", "pdd=>size=10;autoexpire=120")
# call: snapshot of original INVITE fields ($rU/$fU/$si) keyed by Call-ID.
# Why: the http_async_client callback for /route runs in a separate worker
# and reads pseudo-vars against a degraded SIP message context — $rU
# evaluates to the placeholder "you" instead of the dialed number, which
# silently corrupts every relayed INVITE. Stashing into htable before the
# async call and reading back inside the callback bypasses the bug.
# autoexpire=300 = 5 min (longer than any plausible setup+ringing time).
modparam("htable", "htable", "call=>size=12;autoexpire=300")
# rcache: in-process cache of /route responses. Key = "<dialer_ip>:<6-digit DNIS prefix>"
# Value = the JSON body from /api/v1/agent/route. TTL is short (config-driven, default 5s)
# so routing changes propagate quickly while still absorbing burst load. Without this
# every INVITE requires an HTTP round-trip to the control plane (~50-200ms per call),
# capping single-SipProxy throughput at ~150 INVITE/s. With cache hit-rate ~95%+
# (typical for dialer traffic) the ceiling moves to thousands of INVITE/s.
{{ROUTE_CACHE_HTABLE}}

####### http_async_client: control-plane #######
modparam("http_async_client", "tls_verify_host", 0)
modparam("http_async_client", "tls_verify_peer", 0)

####### rtpengine #######
modparam("rtpengine", "rtpengine_sock", "{{RTPENGINE_SOCK}}")

####### siptrace → HOMER (HEP3) #######
# Mirror every SIP message routed through this proxy to heplify-server on
# the base-app. UDP/9060. capture_id distinguishes this node's traffic in
# HOMER when multiple SipProxy nodes are deployed.
modparam("siptrace", "duplicate_uri", "sip:{{HOMER_HEP_HOST}}:9060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 3)
modparam("siptrace", "hep_capture_id", {{HOMER_CAPTURE_ID}})
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "trace_on", 1)
# trace_mode=1 means "trace every message" — no need to call sip_trace()
# in script. Safer than per-route tracing for SIP-ladder completeness.
modparam("siptrace", "trace_mode", 1)

####### request route #######
request_route {
    xlog("L_NOTICE", "mp-recv: $rm from $si:$sp ruri=$ru\n");
    # Answer OPTIONS pings FIRST, before any sanity / scanner / rate-limit
    # checks. Asterisk-based dialers (Vicidial, FreePBX, etc.) use qualify
    # OPTIONS as their trunk-health probe. If we silently drop these (which
    # sanity_check will do for any header it doesn't like) Asterisk marks
    # the peer UNAVAILABLE within seconds and every Dial() returns
    # CHANUNAVAIL without sending an INVITE. So OPTIONS goes BEFORE
    # sanity_check.
    if (is_method("OPTIONS")) {
        xlog("L_NOTICE", "mp-options: replying 200 to $si\n");
        sl_send_reply("200","OK");
        exit;
    }

    # 0. early rejections
    if (!mf_process_maxfwd_header("10")) { sl_send_reply("483","Too Many Hops"); exit; }
    if (!sanity_check()) { exit; }
    if (!is_method("INVITE|ACK|BYE|CANCEL")) {
        sl_send_reply("405","Method Not Allowed"); exit;
    }

    # SIP-layer hardening
    if ($hdr(User-Agent) =~ "(friendly-scanner|sipvicious|sipsak|sundayddr|sundayddr-scanner|VaxIPUserAgent)") {
        $sht(blocked=>$si) = 1;
        xlog("L_NOTICE", "blocked scanner UA from $si\n");
        exit;
    }
    if ($sht(blocked=>$si) != $null) { exit; }
    if (!pike_check_req()) {
        xlog("L_NOTICE", "pike: rate limit hit for $si\n");
        $sht(blocked=>$si) = 1;
        exit;
    }

    # Fire /call-end for ANY BYE or CANCEL — must run BEFORE loose_route()
    # because Asterisk/Vicidial sometimes sends BYEs without Route headers
    # (loose_route() returns false → previously fell through to 405 with
    # no /call-end notification → active_calls grew unbounded). Doing this
    # up-front means every BYE/CANCEL closes the call regardless of dialog
    # routing state.
    if (is_method("BYE")) {
        setflag(1);
        $var(end_body) = "{\"call_id\":\"" + $ci + "\",\"sip_code\":200}";
        $http_req(method) = "POST";
        $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
        $http_req(hdr) = "Content-Type: application/json";
        $http_req(body) = $var(end_body);
        $http_req(suspend) = 0;
        http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-end", "CALL_END_REPLY");
        {{RTPENGINE_DELETE_ON_BYE}}
    }
    if (is_method("CANCEL")) {
        $var(end_body) = "{\"call_id\":\"" + $ci + "\",\"sip_code\":487}";
        $http_req(method) = "POST";
        $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
        $http_req(hdr) = "Content-Type: application/json";
        $http_req(body) = $var(end_body);
        $http_req(suspend) = 0;
        http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-end", "CALL_END_REPLY");
    }

    # In-dialog routing (BYE/ACK/re-INVITE with Route headers)
    if (loose_route()) {
        # Mid-call re-INVITE detection — privacy signal for the panel.
        # In-dialog INVITE means the call's already established and one
        # leg is renegotiating SDP (NAT roam, conference join, fork, or
        # a third-party bridge). We POST the new SDP body so the backend
        # can record the endpoint delta and surface an alert.
        if (is_method("INVITE")) {
            $var(sdp_b64) = $(rb{s.encode.base64});
            $var(ri_body) = "{\"call_id\":\"" + $ci + "\",\"sdp_b64\":\"" + $var(sdp_b64) + "\"}";
            $http_req(method) = "POST";
            $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
            $http_req(hdr) = "Content-Type: application/json";
            $http_req(body) = $var(ri_body);
            $http_req(suspend) = 0;
            http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-reinvite", "CALL_REINVITE_REPLY");
        }
        t_relay();
        exit;
    }

    # Non-routed BYE/CANCEL: still need to relay or terminate. For BYE
    # without Route headers, t_relay() tries to forward by R-URI which
    # works for our setup (R-URI points at the other leg's endpoint).
    if (is_method("BYE") || is_method("CANCEL")) {
        t_relay();
        exit;
    }

    if (!is_method("INVITE")) {
        sl_send_reply("405","Method Not Allowed");
        exit;
    }

    # /route cache lookup — if we already have a recent answer for this
    # client+DNIS-prefix, skip the HTTP round-trip entirely.
    {{ROUTE_CACHE_CHECK}}

    # Absorb retransmissions and send 100 Trying immediately. Without
    # this, Asterisk's T1=500ms retransmit timer fires before our async
    # /route lookup returns, and each retransmission re-enters
    # request_route and spawns ANOTHER http_async_query against the same
    # Call-ID. tm then queues each callback as a new branch on the same
    # transaction; after 12 branches it dies with
    #   ERROR: tm [t_fwd.c:787]: add_uac(): maximum number of branches exceeded
    # and the call never relays. t_newtran() makes tm own the
    # transaction so duplicates get absorbed (return code 0), and the
    # 100 Trying stops Asterisk from retransmitting at all.
    t_newtran();
    if ($retcode == 0) {
        # Retransmission already absorbed by tm — drop silently.
        exit;
    }
    if ($retcode < 0) {
        sl_reply_error();
        exit;
    }
    t_reply("100", "Trying");

    # Snapshot original INVITE fields keyed by Call-ID. The /route
    # async callback reads these back instead of $rU/$fU/$si because
    # those pseudovars resolve against a degraded message context in
    # the callback worker (symptom: $rU becomes the placeholder "you").
    $sht(call=>$ci::dnis) = $rU;
    $sht(call=>$ci::ani)  = $fU;
    $sht(call=>$ci::sig)  = $si;

    # 1. async route lookup against the control plane. The control plane
    # requires bearer auth; we use the per-node agent token (the same one
    # call-start / call-end use below). Kamailio 5.8 dropped the legacy
    # 3-arg http_async_query — body + headers are now set via $http_req()
    # pseudovars and the call itself is 2-arg.
    $var(qs) = "src_ip=" + $si + "&dnis=" + $rU;
    $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
    http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/route?" + $var(qs), "ROUTE_REPLY");
    exit;
}

route[ROUTE_REPLY] {
    xlog("L_NOTICE", "mp-route-reply: http_ok=$http_ok rb=$http_rb\n");
    if ($http_ok == 0) {
        xlog("L_ERR", "http_async_query failed: $http_err\n");
        sl_send_reply("503","Routing unavailable");
        exit;
    }
    # jansson_get sets $var(err) to "<null>" string when the JSON key is
    # absent; the != $null check below alone would treat that as "error
    # present". Probe for the actual SUCCESS keys instead — if signaling_ip
    # came back, the lookup worked.
    jansson_get("signaling_ip", $http_rb, "$var(sig_ip)");
    xlog("L_NOTICE", "mp-route-reply: sig_ip=$var(sig_ip)\n");
    if ($var(sig_ip) == $null || $var(sig_ip) == "<null>" || $var(sig_ip) == "") {
        jansson_get("error", $http_rb, "$var(err)");
        jansson_get("code", $http_rb, "$var(code)");
        xlog("L_NOTICE", "mp-route-reply: err=$var(err) code=$var(code)\n");
        switch ($var(code)) {
            case 403: sl_send_reply("403","Forbidden"); break;
            case 404: sl_send_reply("404","Not Found"); break;
            # 486 = per-client per-lead rate limit hit. Vicidial treats
            # 486 Busy Here as a real busy and won't immediately retry,
            # which is exactly what we want.
            case 486: sl_send_reply("486","Busy Here"); break;
            case 503: sl_send_reply("503","Service Unavailable"); break;
            default:  sl_send_reply("500","Routing Error");
        }
        exit;
    }
    jansson_get("carrier_host",      $http_rb, "$var(c_host)");
    jansson_get("carrier_port",      $http_rb, "$var(c_port)");
    jansson_get("carrier_transport", $http_rb, "$var(c_xport)");
    jansson_get("media_ip",          $http_rb, "$var(m_ip)");
    jansson_get("client_id",         $http_rb, "$var(client_id)");
    jansson_get("carrier_id",        $http_rb, "$var(carrier_id)");

    # Pull snapshot of original INVITE fields (set in request_route).
    # Reading $rU/$fU directly here returns "you"/empty on Kamailio 5.8
    # in async callback context — see htable "call" comment up top.
    $var(dnis_orig) = $sht(call=>$ci::dnis);
    $var(ani_orig)  = $sht(call=>$ci::ani);
    if ($var(dnis_orig) == $null || $var(dnis_orig) == "" || $var(dnis_orig) == "<null>") {
        # htable miss (call expired or never stamped) — fall back to $rU.
        # Better a possibly-wrong user-part than a guaranteed-wrong "you".
        $var(dnis_orig) = $rU;
    }
    if ($var(ani_orig) == $null || $var(ani_orig) == "" || $var(ani_orig) == "<null>") {
        $var(ani_orig) = $fU;
    }

    # Cache the parsed routing fields for the next INVITE from this
    # client+prefix. Empty/error responses already exited above.
    {{ROUTE_CACHE_STORE}}

    # Hand off to the shared relay subroutine. DO_RELAY does the
    # rtpengine offer, call-start fire-and-forget, $ru rewrite, and
    # t_relay. Cache-hit path also calls DO_RELAY directly with the
    # same $var()s populated from the htable, sharing 100% of the
    # relay code between hot- and cold-path.
    route(DO_RELAY);
}

# DO_RELAY: the post-routing relay logic. Expects these $var()s set:
#   client_id, carrier_id, c_host, c_port, c_xport,
#   m_ip, sig_ip, dnis_orig, ani_orig.
# Called from both ROUTE_REPLY (after parsing /route JSON) and the
# cache-hit branch in request_route. Keeping it as a single subroutine
# means the two code paths can't drift apart over time.
route[DO_RELAY] {
    # 1. force outbound from the client's signaling IP
    $fs = "udp:" + $var(sig_ip) + ":5060";

    # 2. rewrite media. Rendered active when rtpengine_sock is non-local.
    {{RTPENGINE_MANAGE_REQUEST}}

    # 3. notify the control plane: call-start
    $var(sdp_b64) = $(rb{s.encode.base64});
    $var(start_body) = "{\"call_id\":\"" + $ci + "\",\"client_id\":" + $var(client_id)
        + ",\"carrier_id\":" + $var(carrier_id) + ",\"media_ip\":\"" + $var(m_ip)
        + "\",\"signaling_from\":\"" + $var(sig_ip) + "\",\"ani\":\"" + $var(ani_orig)
        + "\",\"dnis\":\"" + $var(dnis_orig) + "\",\"sdp_b64\":\"" + $var(sdp_b64) + "\"}";
    $http_req(method) = "POST";
    $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
    $http_req(hdr) = "Content-Type: application/json";
    $http_req(body) = $var(start_body);
    $http_req(suspend) = 0;
    http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-start", "CALL_START_REPLY");

    # 4. relay. PDD timestamp + $ru rewrite + t_relay.
    $sht(pdd=>$ci) = $TV(s) * 1000 + $TV(u) / 1000;
    $ru = "sip:" + $var(dnis_orig) + "@" + $var(c_host) + ":" + $var(c_port);
    xlog("L_NOTICE", "mp-relay: r-uri=$ru sig=$fs dnis=$var(dnis_orig)\n");
    t_on_reply("ROUTE_REPLIES");
    t_relay();
}

route[CALL_START_REPLY] { return; }
route[CALL_PROGRESS_REPLY] { return; }

onreply_route[ROUTE_REPLIES] {
    # rtpengine_manage() on 18x/200 replies. Rendered active or
    # commented based on rtpengine_sock — see request-route block above.
    {{RTPENGINE_MANAGE_REPLY}}

    # Final non-2xx reply: call setup failed. Notify /call-end so the
    # node_ips counter decrements (call-start already incremented it).
    # 4xx/5xx/6xx classes only — provisional 1xx and success 2xx are
    # not terminal.
    if (status =~ "^[456]") {
        $var(end_body) = "{\"call_id\":\"" + $ci + "\",\"sip_code\":" + $rs + "}";
        $http_req(method) = "POST";
        $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
        $http_req(hdr) = "Content-Type: application/json";
        $http_req(body) = $var(end_body);
        $http_req(suspend) = 0;
        http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-end", "CALL_END_REPLY");
    }
    # PDD: fire only on first 18x for this dialog. Once we report it,
    # null the htable entry so retransmits / re-INVITEs don't overwrite.
    if (status =~ "^18[03]$" && $sht(pdd=>$ci) != $null) {
        $var(now_ms) = $TV(s) * 1000 + $TV(u) / 1000;
        $var(pdd_ms) = $var(now_ms) - $sht(pdd=>$ci);
        $sht(pdd=>$ci) = $null;
        if ($var(pdd_ms) >= 0 && $var(pdd_ms) <= 120000) {
            $var(prog_body) = "{\"call_id\":\"" + $ci + "\",\"pdd_ms\":" + $var(pdd_ms) + "}";
            $http_req(method) = "POST";
            $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
            $http_req(hdr) = "Content-Type: application/json";
            $http_req(body) = $var(prog_body);
            $http_req(suspend) = 0;
            http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-progress", "CALL_PROGRESS_REPLY");
        }
    }
}

# BYE → notify control plane: call-end
event_route[tm:local-request] {
    if (is_method("BYE")) {
        $var(end_body) = "{\"call_id\":\"" + $ci + "\",\"sip_code\":200}";
        $http_req(method) = "POST";
        $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
        $http_req(hdr) = "Content-Type: application/json";
        $http_req(body) = $var(end_body);
        $http_req(suspend) = 0;
        http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-end", "CALL_END_REPLY");
    }
}

route[CALL_END_REPLY] { return; }
route[CALL_REINVITE_REPLY] { return; }
`
