package agent

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// GenKamailioConfig writes the listen.cfg fragment (one listen= per signaling
// IP) and the main kamailio.cfg that:
//   - calls our /route endpoint via http_async_client
//   - forces outbound INVITEs from the chosen signaling IP via $fs
//   - rewrites media via rtpengine_manage()
//   - relays to the chosen carrier
// SIP-layer hardening (pike per-source CPS, htable blocklist, drop scanner UAs)
// is built in.
//
// listenIPs is the set of signaling IPs bound on this node (already deduped).
func GenKamailioConfig(listenIPs []string, controlPlaneURL, agentToken string) (listenCfg string, mainCfg string) {
	uniq := make([]string, 0, len(listenIPs))
	seen := map[string]struct{}{}
	for _, ip := range listenIPs {
		if _, dup := seen[ip]; dup || ip == "" {
			continue
		}
		seen[ip] = struct{}{}
		uniq = append(uniq, ip)
	}
	sort.Strings(uniq)

	var lb strings.Builder
	fmt.Fprintf(&lb, "# Generated by mediaproxy node-agent. Do not edit by hand.\n")
	for _, ip := range uniq {
		fmt.Fprintf(&lb, "listen=udp:%s:5060\n", ip)
		fmt.Fprintf(&lb, "listen=tcp:%s:5060\n", ip)
	}
	listenCfg = lb.String()

	mainCfg = strings.ReplaceAll(kamailioMainTmpl, "{{CONTROL_PLANE_URL}}", controlPlaneURL)
	mainCfg = strings.ReplaceAll(mainCfg, "{{AGENT_TOKEN}}", agentToken)
	return
}

// WriteKamailioConfigs writes both files and triggers a graceful reload of
// kamailio (the unit's ExecReload usually sends SIGUSR1 which re-reads
// the cfg).
func WriteKamailioConfigs(listenPath, mainPath, listenCfg, mainCfg string) error {
	if err := os.MkdirAll("/etc/kamailio", 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(listenPath, []byte(listenCfg), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", listenPath, err)
	}
	if err := os.WriteFile(mainPath, []byte(mainCfg), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", mainPath, err)
	}
	return nil
}

const kamailioMainTmpl = `#!KAMAILIO
####### mediaproxy SIP proxy (auto-generated; do not edit) #######
# - per-call route lookup via http_async_client → control plane
# - force-send-socket to per-client signaling IP
# - rtpengine for media rewrite
# - pike + htable scanner block + UA filter

#!define MULTIDOMAIN 0
debug=2
log_stderror=no
log_facility=LOG_LOCAL0
fork=yes
children=8
auto_aliases=no
mpath="/usr/lib/x86_64-linux-gnu/kamailio/modules/"
sip_warning=no

include_file "/etc/kamailio/listen.cfg"

####### modules #######
loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "rr.so"
loadmodule "pv.so"
loadmodule "maxfwd.so"
loadmodule "textops.so"
loadmodule "textopsx.so"
loadmodule "siputils.so"
loadmodule "xlog.so"
loadmodule "sanity.so"
loadmodule "ctl.so"
loadmodule "pike.so"
loadmodule "htable.so"
loadmodule "http_async_client.so"
loadmodule "jansson.so"
loadmodule "rtpengine.so"
loadmodule "acc.so"

####### pike: per-source-IP CPS limiter #######
modparam("pike", "sampling_time_unit", 2)
modparam("pike", "reqs_density_per_unit", 60)
modparam("pike", "remove_latency", 4)

####### htable: scanner blocklist #######
modparam("htable", "htable", "blocked=>size=12;autoexpire=86400")

####### http_async_client: control-plane #######
modparam("http_async_client", "tls_verify_host", 0)
modparam("http_async_client", "tls_verify_peer", 0)

####### rtpengine #######
modparam("rtpengine", "rtpengine_sock", "udp:127.0.0.1:2223")

####### acc → http: CDRs #######
modparam("acc", "log_flag", 1)
modparam("acc", "log_extra", "src_ip=$si;dst_uri=$ru;sip_code=$rs;duration=$DLG_duration")

####### request route #######
request_route {
    # 0. early rejections
    if (!mf_process_maxfwd_header("10")) { sl_send_reply("483","Too Many Hops"); exit; }
    if (!sanity_check()) { exit; }
    if (!is_method("INVITE|ACK|BYE|CANCEL|OPTIONS")) {
        sl_send_reply("405","Method Not Allowed"); exit;
    }

    # SIP-layer hardening
    if ($hdr(User-Agent) =~ "(friendly-scanner|sipvicious|sipsak|sundayddr|sundayddr-scanner|VaxIPUserAgent)") {
        $sht(blocked=>$si) = 1;
        xlog("L_NOTICE", "blocked scanner UA from $si\n");
        exit;
    }
    if ($sht(blocked=>$si) != $null) { exit; }
    if (!pike_check_req()) {
        xlog("L_NOTICE", "pike: rate limit hit for $si\n");
        $sht(blocked=>$si) = 1;
        exit;
    }

    # In-dialog routing
    if (loose_route()) {
        if (is_method("BYE")) { setflag(1); }
        t_relay();
        exit;
    }

    if (is_method("OPTIONS")) {
        sl_send_reply("200","OK");
        exit;
    }

    if (!is_method("INVITE")) {
        sl_send_reply("405","Method Not Allowed");
        exit;
    }

    # 1. async route lookup against the control plane. The control plane
    # requires bearer auth; we use the per-node agent token (the same one
    # call-start / call-end use below). The header is set per-request via
    # the writeable pseudo-variable $http_req(headers).
    $var(qs) = "src_ip=" + $si + "&dnis=" + $rU;
    $http_req(all_hdrs) = "Authorization: Bearer {{AGENT_TOKEN}}\r\n";
    http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/route?" + $var(qs), "ROUTE_REPLY");
    exit;
}

route[ROUTE_REPLY] {
    if ($http_ok == 0) {
        xlog("L_ERR", "http_async_query failed: $http_err\n");
        sl_send_reply("503","Routing unavailable");
        exit;
    }
    jansson_get("error", $http_rb, "$var(err)");
    if ($var(err) != $null) {
        jansson_get("code", $http_rb, "$var(code)");
        switch ($var(code)) {
            case 403: sl_send_reply("403","Forbidden"); break;
            case 404: sl_send_reply("404","Not Found"); break;
            # 486 = per-client per-lead rate limit hit. Vicidial treats
            # 486 Busy Here as a real busy and won't immediately retry,
            # which is exactly what we want.
            case 486: sl_send_reply("486","Busy Here"); break;
            case 503: sl_send_reply("503","Service Unavailable"); break;
            default:  sl_send_reply("500","Routing Error");
        }
        exit;
    }
    jansson_get("signaling_ip",      $http_rb, "$var(sig_ip)");
    jansson_get("carrier_host",      $http_rb, "$var(c_host)");
    jansson_get("carrier_port",      $http_rb, "$var(c_port)");
    jansson_get("carrier_transport", $http_rb, "$var(c_xport)");
    jansson_get("media_ip",          $http_rb, "$var(m_ip)");
    jansson_get("client_id",         $http_rb, "$var(client_id)");
    jansson_get("carrier_id",        $http_rb, "$var(carrier_id)");

    # 2. force outbound from the client's signaling IP
    $fs = "udp:" + $var(sig_ip) + ":5060";

    # 3. rewrite media to the chosen media IP
    rtpengine_manage("replace-origin replace-session-connection out-iface=" + $var(m_ip));

    # 4. notify the control plane: call-start
    # SDP body is base64-encoded so we don't have to JSON-escape newlines,
    # quotes, slashes. The base64 alphabet is JSON-string-safe by itself.
    # Backend decodes + parses m= transport, c= endpoint, a=crypto: suite
    # for the Privacy Monitor.
    $var(sdp_b64) = $(rb{s.encode.b64});
    $var(start_body) = "{\"call_id\":\"" + $ci + "\",\"client_id\":" + $var(client_id)
        + ",\"carrier_id\":" + $var(carrier_id) + ",\"media_ip\":\"" + $var(m_ip)
        + "\",\"signaling_from\":\"" + $var(sig_ip) + "\",\"ani\":\"" + $fU
        + "\",\"dnis\":\"" + $rU + "\",\"sdp_b64\":\"" + $var(sdp_b64) + "\"}";
    $http_req(all_hdrs) = "Authorization: Bearer {{AGENT_TOKEN}}\r\nContent-Type: application/json\r\n";
    http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-start", $var(start_body), "CALL_START_REPLY");

    # 5. relay
    $du = $var(c_xport) + ":" + $var(c_host) + ":" + $var(c_port);
    t_on_reply("ROUTE_REPLIES");
    t_relay();
}

route[CALL_START_REPLY] { }

onreply_route[ROUTE_REPLIES] {
    if (status =~ "(180|183|200)") {
        rtpengine_manage();
    }
}

# BYE → notify control plane: call-end
event_route[tm:local-request] {
    if (is_method("BYE")) {
        $var(end_body) = "{\"call_id\":\"" + $ci + "\",\"sip_code\":200}";
        $http_req(all_hdrs) = "Authorization: Bearer {{AGENT_TOKEN}}\r\nContent-Type: application/json\r\n";
        http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-end", $var(end_body), "CALL_END_REPLY");
    }
}

route[CALL_END_REPLY] { }
`
