package agent

import (
	"fmt"
	"net/url"
	"os"
	"sort"
	"strconv"
	"strings"
)

// GenKamailioConfig writes the listen.cfg fragment (one listen= per signaling
// IP) and the main kamailio.cfg that:
//   - calls our /route endpoint via http_async_client
//   - forces outbound INVITEs from the chosen signaling IP via $fs
//   - rewrites media via rtpengine_manage()
//   - relays to the chosen carrier
//   - mirrors every SIP message as HEP3 to the base-app's heplify-server
//     (used by HOMER for SIP-ladder inspection)
//
// SIP-layer hardening (pike per-source CPS, htable blocklist, drop scanner UAs)
// is built in.
//
// listenIPs is the set of signaling IPs bound on this node (already deduped).
// nodeID is used as the HEP capture-id so HOMER can attribute messages to
// the right proxy when multiple SipProxy nodes are in play.
func GenKamailioConfig(listenIPs []string, controlPlaneURL, agentToken string, nodeID int64) (listenCfg string, mainCfg string) {
	uniq := make([]string, 0, len(listenIPs))
	seen := map[string]struct{}{}
	for _, ip := range listenIPs {
		if _, dup := seen[ip]; dup || ip == "" {
			continue
		}
		seen[ip] = struct{}{}
		uniq = append(uniq, ip)
	}
	sort.Strings(uniq)

	var lb strings.Builder
	fmt.Fprintf(&lb, "# Generated by mediaproxy node-agent. Do not edit by hand.\n")
	for _, ip := range uniq {
		fmt.Fprintf(&lb, "listen=udp:%s:5060\n", ip)
		fmt.Fprintf(&lb, "listen=tcp:%s:5060\n", ip)
	}
	listenCfg = lb.String()

	// HEP destination = the host part of the control-plane URL. heplify-server
	// listens on UDP/9060 on the base-app; kamailio resolves the hostname at
	// load time. If parsing fails we leave it blank and the template will
	// render "sip:" — siptrace just won't push anything, which is the right
	// degraded mode (don't break call routing because HEP capture is unhappy).
	hepHost := ""
	if u, err := url.Parse(controlPlaneURL); err == nil {
		hepHost = u.Hostname()
	}

	mainCfg = strings.ReplaceAll(kamailioMainTmpl, "{{CONTROL_PLANE_URL}}", controlPlaneURL)
	mainCfg = strings.ReplaceAll(mainCfg, "{{AGENT_TOKEN}}", agentToken)
	mainCfg = strings.ReplaceAll(mainCfg, "{{HOMER_HEP_HOST}}", hepHost)
	mainCfg = strings.ReplaceAll(mainCfg, "{{HOMER_CAPTURE_ID}}", strconv.FormatInt(nodeID, 10))
	return
}

// WriteKamailioConfigs writes both files iff their contents differ from
// what's already on disk. Returns changed=true if either file was actually
// rewritten, so the caller can decide whether to bounce the service.
//
// Why: Kamailio's stock systemd unit doesn't support config reload — every
// `systemctl reload-or-restart` is a full restart. With heartbeat at 10s
// the agent was cycling Kamailio every 10s in steady state, which made
// Asterisk's 5s qualify pings half-miss → trunk marked UNREACHABLE →
// CHANUNAVAIL on every Dial(). Skipping the write+restart when the
// content is identical fixes the loop.
func WriteKamailioConfigs(listenPath, mainPath, listenCfg, mainCfg string) (changed bool, err error) {
	if err := os.MkdirAll("/etc/kamailio", 0o755); err != nil {
		return false, err
	}
	listenChanged, err := writeIfChanged(listenPath, listenCfg)
	if err != nil {
		return false, fmt.Errorf("write %s: %w", listenPath, err)
	}
	mainChanged, err := writeIfChanged(mainPath, mainCfg)
	if err != nil {
		return false, fmt.Errorf("write %s: %w", mainPath, err)
	}
	return listenChanged || mainChanged, nil
}

// writeIfChanged compares wanted content to whatever's already on disk and
// writes only on mismatch. Returns true if a write happened.
func writeIfChanged(path, wanted string) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == wanted {
		return false, nil
	}
	if err := os.WriteFile(path, []byte(wanted), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

const kamailioMainTmpl = `#!KAMAILIO
####### mediaproxy SIP proxy (auto-generated; do not edit) #######
# - per-call route lookup via http_async_client → control plane
# - force-send-socket to per-client signaling IP
# - rtpengine for media rewrite
# - pike + htable scanner block + UA filter

#!define MULTIDOMAIN 0
debug=2
log_stderror=no
log_facility=LOG_LOCAL0
fork=yes
children=8
auto_aliases=no
mpath="/usr/lib/x86_64-linux-gnu/kamailio/modules/"
sip_warning=no

include_file "/etc/kamailio/listen.cfg"

####### modules #######
loadmodule "tm.so"
loadmodule "sl.so"
loadmodule "rr.so"
loadmodule "pv.so"
loadmodule "maxfwd.so"
loadmodule "textops.so"
loadmodule "textopsx.so"
loadmodule "siputils.so"
loadmodule "xlog.so"
loadmodule "sanity.so"
loadmodule "ctl.so"
loadmodule "pike.so"
loadmodule "htable.so"
loadmodule "http_async_client.so"
loadmodule "jansson.so"
loadmodule "rtpengine.so"
loadmodule "siptrace.so"

####### pike: per-source-IP CPS limiter #######
modparam("pike", "sampling_time_unit", 2)
modparam("pike", "reqs_density_per_unit", 60)
modparam("pike", "remove_latency", 4)

####### htable: scanner blocklist + PDD timing #######
modparam("htable", "htable", "blocked=>size=12;autoexpire=86400")
# pdd: per-call INVITE timestamp in ms. autoexpire=120 = drop stale entries
# after 2 minutes (way longer than any plausible PDD; 18x always arrives in
# under 30s on every real route, including bad ones).
modparam("htable", "htable", "pdd=>size=10;autoexpire=120")

####### http_async_client: control-plane #######
modparam("http_async_client", "tls_verify_host", 0)
modparam("http_async_client", "tls_verify_peer", 0)

####### rtpengine #######
modparam("rtpengine", "rtpengine_sock", "udp:127.0.0.1:2223")

####### siptrace → HOMER (HEP3) #######
# Mirror every SIP message routed through this proxy to heplify-server on
# the base-app. UDP/9060. capture_id distinguishes this node's traffic in
# HOMER when multiple SipProxy nodes are deployed.
modparam("siptrace", "duplicate_uri", "sip:{{HOMER_HEP_HOST}}:9060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 3)
modparam("siptrace", "hep_capture_id", {{HOMER_CAPTURE_ID}})
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "trace_on", 1)
# trace_mode=1 means "trace every message" — no need to call sip_trace()
# in script. Safer than per-route tracing for SIP-ladder completeness.
modparam("siptrace", "trace_mode", 1)

####### request route #######
request_route {
    xlog("L_NOTICE", "mp-recv: $rm from $si:$sp ruri=$ru\n");
    # Answer OPTIONS pings FIRST, before any sanity / scanner / rate-limit
    # checks. Asterisk-based dialers (Vicidial, FreePBX, etc.) use qualify
    # OPTIONS as their trunk-health probe. If we silently drop these (which
    # sanity_check will do for any header it doesn't like) Asterisk marks
    # the peer UNAVAILABLE within seconds and every Dial() returns
    # CHANUNAVAIL without sending an INVITE. So OPTIONS goes BEFORE
    # sanity_check.
    if (is_method("OPTIONS")) {
        xlog("L_NOTICE", "mp-options: replying 200 to $si\n");
        sl_send_reply("200","OK");
        exit;
    }

    # 0. early rejections
    if (!mf_process_maxfwd_header("10")) { sl_send_reply("483","Too Many Hops"); exit; }
    if (!sanity_check()) { exit; }
    if (!is_method("INVITE|ACK|BYE|CANCEL")) {
        sl_send_reply("405","Method Not Allowed"); exit;
    }

    # SIP-layer hardening
    if ($hdr(User-Agent) =~ "(friendly-scanner|sipvicious|sipsak|sundayddr|sundayddr-scanner|VaxIPUserAgent)") {
        $sht(blocked=>$si) = 1;
        xlog("L_NOTICE", "blocked scanner UA from $si\n");
        exit;
    }
    if ($sht(blocked=>$si) != $null) { exit; }
    if (!pike_check_req()) {
        xlog("L_NOTICE", "pike: rate limit hit for $si\n");
        $sht(blocked=>$si) = 1;
        exit;
    }

    # In-dialog routing
    if (loose_route()) {
        if (is_method("BYE")) { setflag(1); }
        t_relay();
        exit;
    }

    if (!is_method("INVITE")) {
        sl_send_reply("405","Method Not Allowed");
        exit;
    }

    # 1. async route lookup against the control plane. The control plane
    # requires bearer auth; we use the per-node agent token (the same one
    # call-start / call-end use below). Kamailio 5.8 dropped the legacy
    # 3-arg http_async_query — body + headers are now set via $http_req()
    # pseudovars and the call itself is 2-arg.
    $var(qs) = "src_ip=" + $si + "&dnis=" + $rU;
    $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
    http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/route?" + $var(qs), "ROUTE_REPLY");
    exit;
}

route[ROUTE_REPLY] {
    xlog("L_NOTICE", "mp-route-reply: http_ok=$http_ok rb=$http_rb\n");
    if ($http_ok == 0) {
        xlog("L_ERR", "http_async_query failed: $http_err\n");
        sl_send_reply("503","Routing unavailable");
        exit;
    }
    # jansson_get sets $var(err) to "<null>" string when the JSON key is
    # absent; the != $null check below alone would treat that as "error
    # present". Probe for the actual SUCCESS keys instead — if signaling_ip
    # came back, the lookup worked.
    jansson_get("signaling_ip", $http_rb, "$var(sig_ip)");
    xlog("L_NOTICE", "mp-route-reply: sig_ip=$var(sig_ip)\n");
    if ($var(sig_ip) == $null || $var(sig_ip) == "<null>" || $var(sig_ip) == "") {
        jansson_get("error", $http_rb, "$var(err)");
        jansson_get("code", $http_rb, "$var(code)");
        xlog("L_NOTICE", "mp-route-reply: err=$var(err) code=$var(code)\n");
        switch ($var(code)) {
            case 403: sl_send_reply("403","Forbidden"); break;
            case 404: sl_send_reply("404","Not Found"); break;
            # 486 = per-client per-lead rate limit hit. Vicidial treats
            # 486 Busy Here as a real busy and won't immediately retry,
            # which is exactly what we want.
            case 486: sl_send_reply("486","Busy Here"); break;
            case 503: sl_send_reply("503","Service Unavailable"); break;
            default:  sl_send_reply("500","Routing Error");
        }
        exit;
    }
    jansson_get("carrier_host",      $http_rb, "$var(c_host)");
    jansson_get("carrier_port",      $http_rb, "$var(c_port)");
    jansson_get("carrier_transport", $http_rb, "$var(c_xport)");
    jansson_get("media_ip",          $http_rb, "$var(m_ip)");
    jansson_get("client_id",         $http_rb, "$var(client_id)");
    jansson_get("carrier_id",        $http_rb, "$var(carrier_id)");

    # 2. force outbound from the client's signaling IP
    $fs = "udp:" + $var(sig_ip) + ":5060";

    # 3. rewrite media to the chosen media IP. rtpengine_manage() requires
    # rtpengine running on this SipProxy (default sock 127.0.0.1:2223),
    # which on our split SipProxy + MediaNode topology isn't the case.
    # Without a working rtpengine here, this call corrupts transaction
    # state and t_relay never sends the INVITE. SKIPPED until the agent
    # is taught to configure rtpengine_sock to point at the remote media
    # node — separate work. SDP passes through unmodified, which means
    # RTP will flow direct between dialer and carrier without going
    # through MediaNode1. Acceptable for signaling-test phase; before
    # going to production traffic we need rtpengine on this proxy or
    # remote rtpengine_sock configured.
    # rtpengine_manage("replace-origin replace-session-connection out-iface=" + $var(m_ip));

    # 4. notify the control plane: call-start
    # SDP body is base64-encoded so we don't have to JSON-escape newlines,
    # quotes, slashes. The base64 alphabet is JSON-string-safe by itself.
    # Backend decodes + parses m= transport, c= endpoint, a=crypto: suite
    # for the Privacy Monitor.
    $var(sdp_b64) = $(rb{s.encode.base64});
    $var(start_body) = "{\"call_id\":\"" + $ci + "\",\"client_id\":" + $var(client_id)
        + ",\"carrier_id\":" + $var(carrier_id) + ",\"media_ip\":\"" + $var(m_ip)
        + "\",\"signaling_from\":\"" + $var(sig_ip) + "\",\"ani\":\"" + $fU
        + "\",\"dnis\":\"" + $rU + "\",\"sdp_b64\":\"" + $var(sdp_b64) + "\"}";
    $http_req(method) = "POST";
    $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
    $http_req(hdr) = "Content-Type: application/json";
    $http_req(body) = $var(start_body);
    # suspend=0 = fire-and-forget. Otherwise this http_async_query would
    # SUSPEND the SIP transaction, so the subsequent $ru rewrite and
    # t_relay never actually execute with the INVITE's context. Symptom
    # was Kamailio sending an INVITE to "sip:you@<carrier>" (default
    # placeholder URI) because $rU resolved against an empty msg.
    $http_req(suspend) = 0;
    http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-start", "CALL_START_REPLY");

    # 5. relay. Stamp the INVITE timestamp into htable keyed by Call-ID so
    # onreply_route can compute PDD when the first 18x arrives.
    $sht(pdd=>$ci) = $TV(s) * 1000 + $TV(u) / 1000;
    # Rewrite the Request URI to point at the carrier. We use $ru rewrite
    # rather than $du (destination URI override) because Kamailio's TM
    # branch-add was choking on $du in this build — $ru is the more
    # conventional path. The dialed number (user part) stays from $rU;
    # only host:port get rewritten.
    $ru = "sip:" + $rU + "@" + $var(c_host) + ":" + $var(c_port);
    xlog("L_NOTICE", "mp-relay: r-uri=$ru sig=$fs\n");
    t_on_reply("ROUTE_REPLIES");
    t_relay();
}

route[CALL_START_REPLY] { return; }
route[CALL_PROGRESS_REPLY] { return; }

onreply_route[ROUTE_REPLIES] {
    if (status =~ "(180|183|200)") {
        rtpengine_manage();
    }
    # PDD: fire only on first 18x for this dialog. Once we report it,
    # null the htable entry so retransmits / re-INVITEs don't overwrite.
    if (status =~ "^18[03]$" && $sht(pdd=>$ci) != $null) {
        $var(now_ms) = $TV(s) * 1000 + $TV(u) / 1000;
        $var(pdd_ms) = $var(now_ms) - $sht(pdd=>$ci);
        $sht(pdd=>$ci) = $null;
        if ($var(pdd_ms) >= 0 && $var(pdd_ms) <= 120000) {
            $var(prog_body) = "{\"call_id\":\"" + $ci + "\",\"pdd_ms\":" + $var(pdd_ms) + "}";
            $http_req(method) = "POST";
            $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
            $http_req(hdr) = "Content-Type: application/json";
            $http_req(body) = $var(prog_body);
            $http_req(suspend) = 0;
            http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-progress", "CALL_PROGRESS_REPLY");
        }
    }
}

# BYE → notify control plane: call-end
event_route[tm:local-request] {
    if (is_method("BYE")) {
        $var(end_body) = "{\"call_id\":\"" + $ci + "\",\"sip_code\":200}";
        $http_req(method) = "POST";
        $http_req(hdr) = "Authorization: Bearer {{AGENT_TOKEN}}";
        $http_req(hdr) = "Content-Type: application/json";
        $http_req(body) = $var(end_body);
        $http_req(suspend) = 0;
        http_async_query("{{CONTROL_PLANE_URL}}/api/v1/agent/call-end", "CALL_END_REPLY");
    }
}

route[CALL_END_REPLY] { return; }
`
