package agent

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// GenRTPEngineConfig builds a complete rtpengine.conf for the node. It
// sets one interface= line that lists every media IP (rtpengine treats
// "ip1;ip2;ip3" as a multi-interface), opens the RTP port range, and
// enables the NG control socket on 127.0.0.1:2223 for Kamailio.
//
// We deliberately overwrite the whole file — running it through systemd
// reload picks up the new interface set without dropping in-flight calls.
func GenRTPEngineConfig(mediaIPs []string) string {
	uniq := make([]string, 0, len(mediaIPs))
	seen := map[string]struct{}{}
	for _, ip := range mediaIPs {
		if _, dup := seen[ip]; dup || ip == "" {
			continue
		}
		seen[ip] = struct{}{}
		uniq = append(uniq, ip)
	}
	sort.Strings(uniq)

	var b strings.Builder
	fmt.Fprintln(&b, "# Generated by mediaproxy node-agent. Do not edit by hand.")
	fmt.Fprintln(&b, "[rtpengine]")
	if len(uniq) > 0 {
		fmt.Fprintf(&b, "interface = %s\n", strings.Join(uniq, ";"))
	} else {
		fmt.Fprintln(&b, "# (no managed IPs yet — set 'interface =' once they appear)")
	}
	fmt.Fprintln(&b, "listen-ng = 127.0.0.1:2223")
	fmt.Fprintln(&b, "port-min = 30000")
	fmt.Fprintln(&b, "port-max = 60000")
	fmt.Fprintln(&b, "log-level = 6")
	fmt.Fprintln(&b, "table = 0")
	fmt.Fprintln(&b, "tos = 184")
	fmt.Fprintln(&b, "delete-delay = 30")
	return b.String()
}

// WriteRTPEngineConfig writes the rtpengine.conf only if its content
// differs from disk. Returns changed=true if a write actually happened,
// so the caller can avoid bouncing rtpengine when there's nothing to do.
// See WriteKamailioConfigs for the longer rationale — same "every tick
// is a restart" failure mode.
func WriteRTPEngineConfig(path, body string) (changed bool, err error) {
	if err := os.MkdirAll("/etc/rtpengine", 0o755); err != nil {
		return false, err
	}
	return writeIfChanged(path, body)
}
