package agent

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// GenRTPEngineConfig builds a complete rtpengine.conf for the node. It
// sets one interface= line that lists every media IP (rtpengine treats
// "ip1;ip2;ip3" as a multi-interface), opens the RTP port range, and
// enables the NG control socket on ngListen for Kamailio.
//
// ngListen: bind address for the NG control socket. "127.0.0.1:2223" is
// safe (only local kamailio can reach it). For split-host topology
// where a remote SipProxy must connect, pass an externally reachable
// address (e.g. "0.0.0.0:2223" + firewall restriction).
//
// portMin/portMax: UDP port window for media. 30000-60000 (default)
// gives 30k ports = ~7.5k concurrent calls (4 ports per call). For
// higher per-node concurrency expand to 1024-65535 (~15k concurrent).
// Zero values mean "use defaults".
//
// We deliberately overwrite the whole file — running it through systemd
// reload picks up the new interface set without dropping in-flight calls.
func GenRTPEngineConfig(mediaIPs []string, ngListen string, portMin, portMax int) string {
	if ngListen == "" {
		ngListen = "127.0.0.1:2223"
	}
	if portMin <= 0 {
		portMin = 30000
	}
	if portMax <= 0 {
		portMax = 60000
	}
	uniq := make([]string, 0, len(mediaIPs))
	seen := map[string]struct{}{}
	for _, ip := range mediaIPs {
		if _, dup := seen[ip]; dup || ip == "" {
			continue
		}
		seen[ip] = struct{}{}
		uniq = append(uniq, ip)
	}
	sort.Strings(uniq)

	var b strings.Builder
	fmt.Fprintln(&b, "# Generated by mediaproxy node-agent. Do not edit by hand.")
	fmt.Fprintln(&b, "[rtpengine]")
	if len(uniq) > 0 {
		// NAMED interfaces (name/IP) so Kamailio can pick a specific
		// outbound IP per-call via `out-iface=<name>`. With anonymous
		// `interface = IP1;IP2;...`, rtpengine ignores `out-iface=`
		// values and always uses the first listed interface — making
		// IP rotation impossible (every call would egress on IP1).
		// The convention `<IP>/<IP>` gives each interface a name equal
		// to its IP, so `out-iface=67.215.233.95` matches cleanly.
		named := make([]string, len(uniq))
		for i, ip := range uniq {
			named[i] = ip + "/" + ip
		}
		fmt.Fprintf(&b, "interface = %s\n", strings.Join(named, ";"))
	} else {
		fmt.Fprintln(&b, "# (no managed IPs yet — set 'interface =' once they appear)")
	}
	fmt.Fprintf(&b, "listen-ng = %s\n", ngListen)
	fmt.Fprintf(&b, "port-min = %d\n", portMin)
	fmt.Fprintf(&b, "port-max = %d\n", portMax)
	fmt.Fprintln(&b, "log-level = 6")
	fmt.Fprintln(&b, "table = 0")
	fmt.Fprintln(&b, "tos = 184")
	fmt.Fprintln(&b, "delete-delay = 30")
	return b.String()
}

// WriteRTPEngineConfig writes the rtpengine.conf only if its content
// differs from disk. Returns changed=true if a write actually happened,
// so the caller can avoid bouncing rtpengine when there's nothing to do.
// See WriteKamailioConfigs for the longer rationale — same "every tick
// is a restart" failure mode.
func WriteRTPEngineConfig(path, body string) (changed bool, err error) {
	if err := os.MkdirAll("/etc/rtpengine", 0o755); err != nil {
		return false, err
	}
	return writeIfChanged(path, body)
}
