package agent

import (
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

// UpdateRTPEngineInterfaces rewrites the interface= line in rtpengine.conf to
// the given IPs (joined with ';'), then reloads rtpengine. Idempotent.
func UpdateRTPEngineInterfaces(confPath string, ips []string) error {
	if len(ips) == 0 {
		return nil
	}
	sorted := append([]string(nil), ips...)
	sort.Strings(sorted)
	newLine := "interface = " + strings.Join(sorted, ";")

	b, err := os.ReadFile(confPath)
	if err != nil {
		// rtpengine not present on this node — that's fine.
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read rtpengine conf: %w", err)
	}
	lines := strings.Split(string(b), "\n")
	replaced := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "interface") && strings.Contains(trimmed, "=") {
			lines[i] = newLine
			replaced = true
			break
		}
	}
	if !replaced {
		lines = append(lines, newLine)
	}
	if err := os.WriteFile(confPath, []byte(strings.Join(lines, "\n")), 0o644); err != nil {
		return fmt.Errorf("write rtpengine conf: %w", err)
	}
	// Try a graceful reload; fall back to restart only if reload isn't supported.
	if out, err := exec.Command("systemctl", "reload-or-restart", "rtpengine").CombinedOutput(); err != nil {
		return fmt.Errorf("rtpengine reload: %w (%s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// UpdateKamailioListen regenerates /etc/kamailio/listen.cfg with one
// "listen=udp:IP:5060" per managed IP. Caller decides whether to restart
// Kamailio (operator typically batches restarts during low-traffic windows).
func UpdateKamailioListen(path string, ips []string) error {
	sorted := append([]string(nil), ips...)
	sort.Strings(sorted)
	var b strings.Builder
	b.WriteString("# Generated by node-agent. Do not edit by hand.\n")
	for _, ip := range sorted {
		fmt.Fprintf(&b, "listen=udp:%s:5060\n", ip)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write kamailio listen tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename kamailio listen: %w", err)
	}
	return nil
}
